#include <stdio.h>
#include <string.h>
#include <ctype.h>
//#include "mbed.h"
#include <time.h>

//DigitalOut meuLed(LED1);

void encriptar(char *chave, char* texto){
    int chaveLength = strlen(chave); 
    int textoLength = strlen(texto); 
  
    for (int i = 0; i < textoLength; i++) {
        char letraChave = chave[i % chaveLength]; 
        texto[i] = texto[i] > 64 ? (texto[i] + letraChave) % 26 + 65 : texto[i]; 
    }
}

void wrapEncriptar(int inicio, char *buffer) {
    char texto[8000] = "LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.QUISQUEETJUSTOAPURUSCONVALLISFEUGIATQUISNECQUAM.DONECSEDLOBORTISSEM.NAMELEIFENDJUSTOAVELITIACULISEFFICITUR.CRASSODALES,QUAMVITAEMOLLISALIQUAM,LIGULALEOINTERDUMEST,IDMAXIMUSAUGUEDOLORSEDLIBERO.MORBIEUMAURISLECTUS.CURABITURSITAMETMAGNASOLLICITUDIN,LACINIALIBEROINTERDUM,MOLESTIEVELIT.DONECPORTTITORIDSAPIENINULTRICES.SEDQUISQUAMSITAMETANTEULTRICIESINTERDUMQUISQUISURNA.PRAESENTEUISMODLOBORTISNIBHSEDFACILISIS.ETIAMMATTISMAURISSEM,ACPOSUERENEQUEBIBENDUMEU.VESTIBULUMSODALESEFFICITURQUAM,NONACCUMSANFELIS.VIVAMUSETAUGUEINLEOAUCTORFAUCIBUSETELEMENTUMENIM.DONECTRISTIQUEFRINGILLANEQUE,VELELEIFENDNISIAUCTORID.ETIAMVELNUNCETLACUSRUTRUMVIVERRA.SUSPENDISSEPELLENTESQUELOREMIDMASSARHONCUS,NONALIQUETODIOLAOREET.PRAESENTUTVEHICULAARCU.PROINEGETMOLLISMASSA,VELCONSECTETUREX.PROINANTEMI,ALIQUETSITAMETTEMPUSNEC,DICTUMTEMPUSODIO.SEDAUGUEEST,CONDIMENTUMACALIQUAMEGET,CURSUSAJUSTO.INTEGERGRAVIDAANTEMAGNA,NECCONDIMENTUMLOREMFEUGIATET.DONECEGESTASPELLENTESQUEMOLLIS.PELLENTESQUEETELITIDSEMPOSUERECONSECTETURUTETURNA.AENEANPLACERATFACILISISTORTOR,IDPORTTITORDOLORCONGUEUT.NUNCBLANDITPULVINARVELIT,FEUGIATMATTISNULLAFAUCIBUSSED.UTNONNISLEGETNISIPLACERATDICTUMQUISEUTURPIS.VIVAMUSUTSODALESNUNC,ACSOLLICITUDINODIO.INTEGERSEDNIBHCURSUS,PLACERATANTEAC,IMPERDIETPURUS.PROINEGESTASAUGUEVELSAPIENVESTIBULUM,EUIACULISEXMOLESTIE.MAECENASIDRISUSULTRICIES,PLACERATODIOA,PORTAARCU.ETIAMATLOREMRHONCUS,IACULISESTAT,DIGNISSIMLIBERO.PELLENTESQUEDAPIBUSPULVINARLACINIA.PRAESENTBIBENDUM,NEQUEQUISULTRICIESLAOREET,LACUSEXTRISTIQUEDIAM,NONCURSUSEXDOLORINTORTOR.FUSCELACUSEST,ULTRICESMALESUADACONGUEEGET,SODALESINTURPIS.NULLAMEGETNISIACRISUSEUISMODLAOREET.SUSPENDISSEETALIQUAMVELIT.UTSODALESLOBORTISRISUSCURSUSDICTUM.PHASELLUSEUMOLESTIEIPSUM,IDRUTRUMLECTUS.PRAESENTCURSUSCOMMODOERATSEDHENDRERIT.CURABITURVIVERRATELLUSVITAELACUSAUCTOREUISMOD.PRAESENTEGETSEMNULLA.PELLENTESQUEACELITMASSA.NAMARISUSNIBH.PELLENTESQUEACCUMSANNIBHVELPORTTITORVARIUS.SEDELEMENTUMELEMENTUMDUIVELELEIFEND.CRASPLACERATSAPIENVELNISITINCIDUNT,VITAETINCIDUNTLOREMPRETIUM.INELEMENTUMDUIUTDICTUMHENDRERIT.DONECGRAVIDAQUISTELLUSIDDICTUM.MAECENASNECQUAMNISI.MAECENASTURPISSAPIEN,LUCTUSACSAPIENET,VIVERRAPHARETRAMETUS.VIVAMUSCONDIMENTUMARCUIDCOMMODOCOMMODO.VESTIBULUMTINCIDUNTTURPISEUARCUVENENATIS,EGETTRISTIQUENISILAOREET.PRAESENTTINCIDUNT,EROSVELSOLLICITUDINLUCTUS,MASSASEMDIGNISSIMNISI,SEDLUCTUSLIBERONISIETAUGUE.SEDEGETMOLLISEX.NULLAAESTNECNISIPULVINARRHONCUSIDVITAEEX.PROINVITAEEUISMODMI.FUSCEVITAESODALESTURPIS.VIVAMUSSODALESENIMEGETVOLUTPATLAOREET.INTEGERSITAMETORCIETANTELOBORTISFAUCIBUSSITAMETNONEROS.NAMVARIUSNECNIBHNECSEMPER.DUISIMPERDIETERATETPULVINARDIGNISSIM.NUNCFINIBUSSEDMIQUISVOLUTPAT.FUSCEFAUCIBUSULLAMCORPERGRAVIDA.INPOSUERETEMPORRUTRUM.NUNCDAPIBUSTORTORACPELLENTESQUECONDIMENTUM.FUSCESOLLICITUDINULTRICESLIGULANECINTERDUM.ETIAMAVIVERRAPURUS,VITAERUTRUMIPSUM.SUSPENDISSEPOTENTI.DONECPOSUERECONVALLISNISIUTALIQUET.FUSCESODALESNISIINFELISPRETIUMTINCIDUNT.VESTIBULUMSITAMETMOLLISNEQUE,EGETMALESUADAORCI.MAECENASPULVINARENIMVITAEDOLORTEMPUSMATTIS.INTEGERVITAEFELISLECTUS.NULLAORCIEROS,FEUGIATAULLAMCORPEREGET,ALIQUAMSEDAUGUE.NULLAMSEDULTRICIESMETUS.PELLENTESQUEVITAEAUGUESITAMETDOLORVESTIBULUMCOMMODO.VIVAMUSTINCIDUNTDOLORLIBERO,VELSODALESSEMHENDRERITIN.SUSPENDISSELOBORTISCURSUSSEMPER.CURABITURDICTUMCONSECTETURBIBENDUM.MAECENASCONSECTETURIDVELITINPHARETRA.PELLENTESQUECOMMODOVOLUTPATMAGNA,INULTRICESENIMLACINIAPLACERAT.NULLAMSEDANTEAANTEPELLENTESQUEMOLESTIEETSEDAUGUE.PELLENTESQUEDIGNISSIMSOLLICITUDINPURUSIDDAPIBUS.PELLENTESQUEACACCUMSANERAT.PROINACMETUSNONPURUSFEUGIATVESTIBULUMSEDSITAMETELIT.PHASELLUSHENDRERITULTRICIESMAGNAEUSODALES.PELLENTESQUEHABITANTMORBITRISTIQUESENECTUSETNETUSETMALESUADAFAMESACTURPISEGESTAS.CRASFRINGILLACONSECTETURRISUS,INRUTRUMNISIFRINGILLAET.CLASSAPTENTTACITISOCIOSQUADLITORATORQUENTPERCONUBIANOSTRA,PERINCEPTOSHIMENAEOS.FUSCENECCONGUENISI.FUSCETINCIDUNT,QUAMINEGESTASMAXIMUS,TURPISMASSAMOLLISLECTUS,ETBIBENDUMDIAMSAPIENIDLOREM.DONECETEXVELIT.DONECCURSUSSEMIDDICTUMTINCIDUNT.MORBIACCUMSANQUISLOREMETDICTUM.DONECFACILISISCOMMODONEQUEUTPORTTITOR.PHASELLUSQUISRISUSINANTEFEUGIATBLANDITUTNECRISUS.DONECALIQUAMNIBHLIBERO,EGETVESTIBULUMNULLAMAXIMUSVEL.INTEGERVELITSEM,DIGNISSIMUTPLACERATAT,PORTAEGETANTE.DUISEGETTURPISSEM.QUISQUEFINIBUSULTRICIESDUIACAUCTOR.PROINVELTORTORPHARETRA,MALESUADAMAGNAPRETIUM,MATTISERAT.PHASELLUSMOLESTIETELLUSPORTTITORLIBEROPOSUERERUTRUM.PRAESENTPHARETRAMETUSVITAELOREMCONVALLISBIBENDUM.PRAESENTPHARETRAORCIEGETFACILISISMATTIS.DONECPELLENTESQUENUNCIDEROSVEHICULAIACULIS.DONECETTELLUSIDLOREMEGESTASRHONCUS.SEDERATNEQUE,RUTRUMETEROSEU,SODALESULTRICIESNEQUE.VESTIBULUMIDMASSAVARIUS,CONSECTETURTELLUSQUIS,HENDRERITNULLA.DUISVELTEMPUSSEM.ALIQUAMERATVOLUTPAT.PROINBLANDITALIQUAMELITVITAEFERMENTUM.NAMACNULLAIDTURPISTINCIDUNTEFFICITUREGESTASVITAEDIAM.CURABITUREGETCONDIMENTUMLIBERO,NECCONGUEMETUS.SEDTINCIDUNTATMAURISNONALIQUAM.PHASELLUSEFFICITURARCUSITAMETSODALESPHARETRA.VIVAMUSEUENIMDICTUMNUNCIACULISMAXIMUS.CRASLUCTUSALIQUAMNEQUEVITAECONSEQUAT.VIVAMUSUTMASSAORCI.INHACHABITASSEPLATEADICTUMST.INSAGITTISNEQUEACIACULISULLAMCORPER.AENEANBIBENDUMQUAMSITAMETARCUTEMPUSEUISMOD.ALIQUAMSUSCIPITELITCURSUSVIVERRATRISTIQUE.NAMMAXIMUSSEMATVELITULTRICES,NONCOMMODOMASSAPELLENTESQUE.NULLAELITNIBH,CONSEQUATNONLEOVEL,PULVINARAUCTORLACUS.MAURISCONVALLISVITAEJUSTOTRISTIQUEEUISMOD.DONECALIQUETALIQUAMLIGULA,AMOLESTIEDUIRUTRUMAT.NAMBLANDIT,ELITNECGRAVIDARUTRUM,NIBHSAPIENALIQUETDUI,VITAEFAUCIBUSLIBEROENIMETODIO.PRAESENTCOMMODOORCIFERMENTUMLECTUSMOLLISTEMPOR.SUSPENDISSESUSCIPITVELITSITAMETSUSCIPITGRAVIDA.PHASELLUSSEDMASSAEUMAGNAPHARETRATRISTIQUESEDUTVELIT.MAURISQUISPRETIUMRISUS,IMPERDIETALIQUAMLECTUS.UTRUTRUMDOLORMAGNA,VITAECONSEQUATDOLORCURSUSNON.SUSPENDISSETINCIDUNTDAPIBUSLOBORTIS.PRAESENTAAUCTORTURPIS,VITAELOBORTISELIT.DONECFAUCIBUSLECTUSAFAUCIBUSORNARE.SEDVELMETUSDAPIBUSEXPHARETRAFRINGILLA.NUNCUTFELISGRAVIDA,CONVALLISEXSED,MOLESTIETORTOR.PELLENTESQUEDIGNISSIMLECTUSVITAEORCISUSCIPIT,VENENATISPORTTITORSEMTEMPUS.QUISQUESITAMETSAGITTISENIM.ALIQUAMSITAMETORCIINQUAMFRINGILLAALIQUAM.DONECAUCTORVEHICULATINCIDUNT.CRASTRISTIQUEELITEUQUAMLACINIAORNARE.SEDINFINIBUSLACUS.SUSPENDISSEEUIPSUMNECMAGNAPORTTITOREUISMOD.VIVAMUSULLAMCORPERMATTISALIQUET.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.SEDMALESUADAQUISRISUSIDEFFICITUR.FUSCEVITAELACUSELIT.DONECEUISMODENIMNONAUCTORPULVINAR.FUSCEVIVERRAACCUMSANNULLA.VIVAMUSCONDIMENTUMMOLESTIEJUSTOUTALIQUET.QUISQUEDIGNISSIMPORTAFACILISIS.NULLAMEUISMOD,LECTUSUTELEIFENDSAGITTIS,ODIORISUSELEMENTUMQUAM,EGETSUSCIPITFELISELITQUISNISI.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.INULTRICIESTORTORVELHENDRERITDICTUM.VESTIBULUMVIVERRAVIVERRAIMPERDIET.UTEFFICITURESTNONANTESODALES,SITAMETTEMPORLECTUSULTRICES.SEDHENDRERITVIVERRASAPIENEULACINIA.QUISQUELOREMNISI,MATTISSEDVEHICULAID,LOBORTISACURNA.PRAESENTCONVALLISJUSTOVIVERRAEXVOLUTPATTEMPUS.MAURISCONVALLISEUISMODNIBH,SITAMETSOLLICITUDINENIMPHARETRAAC.DONECLACINIAGRAVIDAMETUS.MAURISQUISPELLENTESQUETURPIS.PELLENTESQUERUTRUM,SEMNECRUTRUMAUCTOR,TELLUSPURUSPORTASEM,ACFACILISISMAURISURNANECAUGUE.NULLAMETFAUCIBUSEX,EGETULTRICIESSEM.NULLAMVENENATISEROSLOREM,VIVERRAULTRICIESDOLORMALESUADAIN.DONECNECTORTORTELLUS.UTVIVERRA,EROSNECFAUCIBUSLACINIA,URNAJUSTOULTRICIESANTE,EGETMAXIMUSFELISLOREMNECNUNC.ETIAMINTERDUMAUGUEQUISLIGULALUCTUS,ATEMPUSFELISSOLLICITUDIN.MAECENASGRAVIDARUTRUMURNAINMOLLIS.SEDINULTRICESAUGUE.FUSCEUTAUGUEETORCIULTRICESPRETIUMEUVELENIM.ALIQUAMASAGITTISIPSUM.SUSPENDISSEBLANDIT,LOREMNECELEIFENDDICTUM,DUILIBEROFAUCIBUSLOREM,NONMOLLISNIBHEXEUNUNC.MAURISDIGNISSIMTEMPUSORCISEDVULPUTATE.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.MAURISCOMMODOFEUGIATMETUSVITAEDIGNISSIM.DONECPELLENTESQUERHONCUSPORTA.AEEANVOLUTPATMASSANONORCIMOLESTIE,EUHENDRERITVELITLAOREET.NAMATINCIDUNTLIBERO,INTINCIDUNTNUNC.ALIQUAMINTERDUMMAURISULLAMCORPER,POSUEREDOLORAC,INTERDUMLEO.AENEANATANTEMETUS.QUISQUEVENENATIS,METUSGRAVIDALUCTUSLOBORTIS,PURUSJUSTODAPIBUSERAT,ACFACILISISVELITARCUNECNISI.MORBIBLANDITPULVINARDIAM,QUISSAGITTISEROSTEMPORA.ETIAMCONSEQUATFEUGIATEROS,SUSCIPITSCELERISQUERISUS.";
    char chave[6] = "PIZZA"; 

    //Timer tempo;

    clock_t start_time, end_time;
    double cpu_time_used;

    start_time = clock();

    //meuLed = 1;
    //tempo.start();
    while (inicio < 8000) { 
        int j = 0; 

        for (int i = 0; i < 10; i++) {
            char c = texto[inicio + i]; 
            if (c == '\0') { break; } 
      
        buffer[i] = c; 

        }
        
        encriptar(chave, buffer); 
        
        inicio += 10; // Incrementa o início para processar a próxima parte do texto
    }

    end_time = clock();

    cpu_time_used = ((double) (end_time - start_time)) / CLOCKS_PER_SEC;

    printf("\n");

    printf("Tempo de CPU usado: %f segundos\n", cpu_time_used);


    //tempo.stop();
    //printf("\nTEMPO encriptar Mbed: %lld microsegundos",tempo.read_high_resolution_us());
    //meuLed = 0;
}

int main() {

    //while(1){
       
        int inicio = 0; // Início da parte
        char buffer[11]; // Buffer para armazenar partes do texto (+1 para o caractere nulo)
        buffer[10] = '\0'; // Garanta que a string seja terminada corretamente

        wrapEncriptar(inicio, buffer); 

        printf("\n");

        //wait_ms(20);
    //}
    return 0;
} 
