/*
 * Aplicação de Criptografia e Descriptografia de Texto
 *
 * Copyright (c) 2023 Marcelo De Araújo and Davison Lucas Mendes Viana
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy 
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights 
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
 * copies of the Software, and to permit persons to whom the Software is 
 * furnished to do so, subject to the following conditions: 
 * The above copyright notice and this permission notice shall be included in all 
 * copies or substantial portions of the Software. 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 * Contato: marcelo.araujo02@aluno.ifce.edu.br
 *
 * Finalidade:
 * Este programa permite, encriptar e desencriptar texto com base em uma chave de criptografia.
 * O código é desenvolvido como parte de um trabalho acadêmico da disciplina Sistemas Embarcados
 * no Instituto Federal do Ceará - Campus Fortaleza e tem como objetivo demonstrar conceitos de 
 * programação para embarcados.
 *
 * Modo de Uso:
 * 
 * Compilação:
 * Para compilar o programa, utilize o compilador GCC (GNU Compiler Collection) ou outro compilador C compatível.
 * 
 * Comando de compilação:
 * gcc cifraDeVigenereMbedOS.c -o cifra
 *
 * Execução:
 * Após a compilação bem-sucedida, execute o programa gerado com o seguinte comando:
 *
 * Comando de execução:
 * ./cifra
 *
 * Entradas:
 * - Nenhuma entrada interativa; o texto é manipulado internamente no código.
 * 
 * Saídas:
 * - Texto original formatado.
 * - Texto encriptado.
 * - Texto desencriptado.
 *
 * Autores/Estudantes:
 * - Marcelo de Araújo
 * - Davison Lucas Mendes Viana
 *
 * Data de Desenvolvimento: 06/11/2023 - 27/11/2023
 *
 * Contexto do Desenvolvimento:
 * - Disciplina: Sistemas Embarcados
 * - Professor: Dr. Elias Teodoro da Silva Junior
 * - Universidade: Instituto Federal do Ceará - Campus Fortaleza
 * - Plataforma Alvo: MbedOS / STM32F030
 *
 */

#include <stdio.h>
#include <string.h>
#include <ctype.h>

/**
 * Função para exibir o texto a ser encriptado, ja tratado, para teste de comparação
 * entre o mesmo e o texto desencriptado.
 * 
 * @param inicio - Um inteiro onde especifica o inicio do array de char.
 * @param conteudo - Um ponteiro de char para processar o texto em partes.
**/

void exibirTextoOriginalFormatado(int inicio, char *buffer) {
    char texto[8000] = "LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.QUISQUEETJUSTOAPURUSCONVALLISFEUGIATQUISNECQUAM.DONECSEDLOBORTISSEM.NAMELEIFENDJUSTOAVELITIACULISEFFICITUR.CRASSODALES,QUAMVITAEMOLLISALIQUAM,LIGULALEOINTERDUMEST,IDMAXIMUSAUGUEDOLORSEDLIBERO.MORBIEUMAURISLECTUS.CURABITURSITAMETMAGNASOLLICITUDIN,LACINIALIBEROINTERDUM,MOLESTIEVELIT.DONECPORTTITORIDSAPIENINULTRICES.SEDQUISQUAMSITAMETANTEULTRICIESINTERDUMQUISQUISURNA.PRAESENTEUISMODLOBORTISNIBHSEDFACILISIS.ETIAMMATTISMAURISSEM,ACPOSUERENEQUEBIBENDUMEU.VESTIBULUMSODALESEFFICITURQUAM,NONACCUMSANFELIS.VIVAMUSETAUGUEINLEOAUCTORFAUCIBUSETELEMENTUMENIM.DONECTRISTIQUEFRINGILLANEQUE,VELELEIFENDNISIAUCTORID.ETIAMVELNUNCETLACUSRUTRUMVIVERRA.SUSPENDISSEPELLENTESQUELOREMIDMASSARHONCUS,NONALIQUETODIOLAOREET.PRAESENTUTVEHICULAARCU.PROINEGETMOLLISMASSA,VELCONSECTETUREX.PROINANTEMI,ALIQUETSITAMETTEMPUSNEC,DICTUMTEMPUSODIO.SEDAUGUEEST,CONDIMENTUMACALIQUAMEGET,CURSUSAJUSTO.INTEGERGRAVIDAANTEMAGNA,NECCONDIMENTUMLOREMFEUGIATET.DONECEGESTASPELLENTESQUEMOLLIS.PELLENTESQUEETELITIDSEMPOSUERECONSECTETURUTETURNA.AENEANPLACERATFACILISISTORTOR,IDPORTTITORDOLORCONGUEUT.NUNCBLANDITPULVINARVELIT,FEUGIATMATTISNULLAFAUCIBUSSED.UTNONNISLEGETNISIPLACERATDICTUMQUISEUTURPIS.VIVAMUSUTSODALESNUNC,ACSOLLICITUDINODIO.INTEGERSEDNIBHCURSUS,PLACERATANTEAC,IMPERDIETPURUS.PROINEGESTASAUGUEVELSAPIENVESTIBULUM,EUIACULISEXMOLESTIE.MAECENASIDRISUSULTRICIES,PLACERATODIOA,PORTAARCU.ETIAMATLOREMRHONCUS,IACULISESTAT,DIGNISSIMLIBERO.PELLENTESQUEDAPIBUSPULVINARLACINIA.PRAESENTBIBENDUM,NEQUEQUISULTRICIESLAOREET,LACUSEXTRISTIQUEDIAM,NONCURSUSEXDOLORINTORTOR.FUSCELACUSEST,ULTRICESMALESUADACONGUEEGET,SODALESINTURPIS.NULLAMEGETNISIACRISUSEUISMODLAOREET.SUSPENDISSEETALIQUAMVELIT.UTSODALESLOBORTISRISUSCURSUSDICTUM.PHASELLUSEUMOLESTIEIPSUM,IDRUTRUMLECTUS.PRAESENTCURSUSCOMMODOERATSEDHENDRERIT.CURABITURVIVERRATELLUSVITAELACUSAUCTOREUISMOD.PRAESENTEGETSEMNULLA.PELLENTESQUEACELITMASSA.NAMARISUSNIBH.PELLENTESQUEACCUMSANNIBHVELPORTTITORVARIUS.SEDELEMENTUMELEMENTUMDUIVELELEIFEND.CRASPLACERATSAPIENVELNISITINCIDUNT,VITAETINCIDUNTLOREMPRETIUM.INELEMENTUMDUIUTDICTUMHENDRERIT.DONECGRAVIDAQUISTELLUSIDDICTUM.MAECENASNECQUAMNISI.MAECENASTURPISSAPIEN,LUCTUSACSAPIENET,VIVERRAPHARETRAMETUS.VIVAMUSCONDIMENTUMARCUIDCOMMODOCOMMODO.VESTIBULUMTINCIDUNTTURPISEUARCUVENENATIS,EGETTRISTIQUENISILAOREET.PRAESENTTINCIDUNT,EROSVELSOLLICITUDINLUCTUS,MASSASEMDIGNISSIMNISI,SEDLUCTUSLIBERONISIETAUGUE.SEDEGETMOLLISEX.NULLAAESTNECNISIPULVINARRHONCUSIDVITAEEX.PROINVITAEEUISMODMI.FUSCEVITAESODALESTURPIS.VIVAMUSSODALESENIMEGETVOLUTPATLAOREET.INTEGERSITAMETORCIETANTELOBORTISFAUCIBUSSITAMETNONEROS.NAMVARIUSNECNIBHNECSEMPER.DUISIMPERDIETERATETPULVINARDIGNISSIM.NUNCFINIBUSSEDMIQUISVOLUTPAT.FUSCEFAUCIBUSULLAMCORPERGRAVIDA.INPOSUERETEMPORRUTRUM.NUNCDAPIBUSTORTORACPELLENTESQUECONDIMENTUM.FUSCESOLLICITUDINULTRICESLIGULANECINTERDUM.ETIAMAVIVERRAPURUS,VITAERUTRUMIPSUM.SUSPENDISSEPOTENTI.DONECPOSUERECONVALLISNISIUTALIQUET.FUSCESODALESNISIINFELISPRETIUMTINCIDUNT.VESTIBULUMSITAMETMOLLISNEQUE,EGETMALESUADAORCI.MAECENASPULVINARENIMVITAEDOLORTEMPUSMATTIS.INTEGERVITAEFELISLECTUS.NULLAORCIEROS,FEUGIATAULLAMCORPEREGET,ALIQUAMSEDAUGUE.NULLAMSEDULTRICIESMETUS.PELLENTESQUEVITAEAUGUESITAMETDOLORVESTIBULUMCOMMODO.VIVAMUSTINCIDUNTDOLORLIBERO,VELSODALESSEMHENDRERITIN.SUSPENDISSELOBORTISCURSUSSEMPER.CURABITURDICTUMCONSECTETURBIBENDUM.MAECENASCONSECTETURIDVELITINPHARETRA.PELLENTESQUECOMMODOVOLUTPATMAGNA,INULTRICESENIMLACINIAPLACERAT.NULLAMSEDANTEAANTEPELLENTESQUEMOLESTIEETSEDAUGUE.PELLENTESQUEDIGNISSIMSOLLICITUDINPURUSIDDAPIBUS.PELLENTESQUEACACCUMSANERAT.PROINACMETUSNONPURUSFEUGIATVESTIBULUMSEDSITAMETELIT.PHASELLUSHENDRERITULTRICIESMAGNAEUSODALES.PELLENTESQUEHABITANTMORBITRISTIQUESENECTUSETNETUSETMALESUADAFAMESACTURPISEGESTAS.CRASFRINGILLACONSECTETURRISUS,INRUTRUMNISIFRINGILLAET.CLASSAPTENTTACITISOCIOSQUADLITORATORQUENTPERCONUBIANOSTRA,PERINCEPTOSHIMENAEOS.FUSCENECCONGUENISI.FUSCETINCIDUNT,QUAMINEGESTASMAXIMUS,TURPISMASSAMOLLISLECTUS,ETBIBENDUMDIAMSAPIENIDLOREM.DONECETEXVELIT.DONECCURSUSSEMIDDICTUMTINCIDUNT.MORBIACCUMSANQUISLOREMETDICTUM.DONECFACILISISCOMMODONEQUEUTPORTTITOR.PHASELLUSQUISRISUSINANTEFEUGIATBLANDITUTNECRISUS.DONECALIQUAMNIBHLIBERO,EGETVESTIBULUMNULLAMAXIMUSVEL.INTEGERVELITSEM,DIGNISSIMUTPLACERATAT,PORTAEGETANTE.DUISEGETTURPISSEM.QUISQUEFINIBUSULTRICIESDUIACAUCTOR.PROINVELTORTORPHARETRA,MALESUADAMAGNAPRETIUM,MATTISERAT.PHASELLUSMOLESTIETELLUSPORTTITORLIBEROPOSUERERUTRUM.PRAESENTPHARETRAMETUSVITAELOREMCONVALLISBIBENDUM.PRAESENTPHARETRAORCIEGETFACILISISMATTIS.DONECPELLENTESQUENUNCIDEROSVEHICULAIACULIS.DONECETTELLUSIDLOREMEGESTASRHONCUS.SEDERATNEQUE,RUTRUMETEROSEU,SODALESULTRICIESNEQUE.VESTIBULUMIDMASSAVARIUS,CONSECTETURTELLUSQUIS,HENDRERITNULLA.DUISVELTEMPUSSEM.ALIQUAMERATVOLUTPAT.PROINBLANDITALIQUAMELITVITAEFERMENTUM.NAMACNULLAIDTURPISTINCIDUNTEFFICITUREGESTASVITAEDIAM.CURABITUREGETCONDIMENTUMLIBERO,NECCONGUEMETUS.SEDTINCIDUNTATMAURISNONALIQUAM.PHASELLUSEFFICITURARCUSITAMETSODALESPHARETRA.VIVAMUSEUENIMDICTUMNUNCIACULISMAXIMUS.CRASLUCTUSALIQUAMNEQUEVITAECONSEQUAT.VIVAMUSUTMASSAORCI.INHACHABITASSEPLATEADICTUMST.INSAGITTISNEQUEACIACULISULLAMCORPER.AENEANBIBENDUMQUAMSITAMETARCUTEMPUSEUISMOD.ALIQUAMSUSCIPITELITCURSUSVIVERRATRISTIQUE.NAMMAXIMUSSEMATVELITULTRICES,NONCOMMODOMASSAPELLENTESQUE.NULLAELITNIBH,CONSEQUATNONLEOVEL,PULVINARAUCTORLACUS.MAURISCONVALLISVITAEJUSTOTRISTIQUEEUISMOD.DONECALIQUETALIQUAMLIGULA,AMOLESTIEDUIRUTRUMAT.NAMBLANDIT,ELITNECGRAVIDARUTRUM,NIBHSAPIENALIQUETDUI,VITAEFAUCIBUSLIBEROENIMETODIO.PRAESENTCOMMODOORCIFERMENTUMLECTUSMOLLISTEMPOR.SUSPENDISSESUSCIPITVELITSITAMETSUSCIPITGRAVIDA.PHASELLUSSEDMASSAEUMAGNAPHARETRATRISTIQUESEDUTVELIT.MAURISQUISPRETIUMRISUS,IMPERDIETALIQUAMLECTUS.UTRUTRUMDOLORMAGNA,VITAECONSEQUATDOLORCURSUSNON.SUSPENDISSETINCIDUNTDAPIBUSLOBORTIS.PRAESENTAAUCTORTURPIS,VITAELOBORTISELIT.DONECFAUCIBUSLECTUSAFAUCIBUSORNARE.SEDVELMETUSDAPIBUSEXPHARETRAFRINGILLA.NUNCUTFELISGRAVIDA,CONVALLISEXSED,MOLESTIETORTOR.PELLENTESQUEDIGNISSIMLECTUSVITAEORCISUSCIPIT,VENENATISPORTTITORSEMTEMPUS.QUISQUESITAMETSAGITTISENIM.ALIQUAMSITAMETORCIINQUAMFRINGILLAALIQUAM.DONECAUCTORVEHICULATINCIDUNT.CRASTRISTIQUEELITEUQUAMLACINIAORNARE.SEDINFINIBUSLACUS.SUSPENDISSEEUIPSUMNECMAGNAPORTTITOREUISMOD.VIVAMUSULLAMCORPERMATTISALIQUET.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.SEDMALESUADAQUISRISUSIDEFFICITUR.FUSCEVITAELACUSELIT.DONECEUISMODENIMNONAUCTORPULVINAR.FUSCEVIVERRAACCUMSANNULLA.VIVAMUSCONDIMENTUMMOLESTIEJUSTOUTALIQUET.QUISQUEDIGNISSIMPORTAFACILISIS.NULLAMEUISMOD,LECTUSUTELEIFENDSAGITTIS,ODIORISUSELEMENTUMQUAM,EGETSUSCIPITFELISELITQUISNISI.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.INULTRICIESTORTORVELHENDRERITDICTUM.VESTIBULUMVIVERRAVIVERRAIMPERDIET.UTEFFICITURESTNONANTESODALES,SITAMETTEMPORLECTUSULTRICES.SEDHENDRERITVIVERRASAPIENEULACINIA.QUISQUELOREMNISI,MATTISSEDVEHICULAID,LOBORTISACURNA.PRAESENTCONVALLISJUSTOVIVERRAEXVOLUTPATTEMPUS.MAURISCONVALLISEUISMODNIBH,SITAMETSOLLICITUDINENIMPHARETRAAC.DONECLACINIAGRAVIDAMETUS.MAURISQUISPELLENTESQUETURPIS.PELLENTESQUERUTRUM,SEMNECRUTRUMAUCTOR,TELLUSPURUSPORTASEM,ACFACILISISMAURISURNANECAUGUE.NULLAMETFAUCIBUSEX,EGETULTRICIESSEM.NULLAMVENENATISEROSLOREM,VIVERRAULTRICIESDOLORMALESUADAIN.DONECNECTORTORTELLUS.UTVIVERRA,EROSNECFAUCIBUSLACINIA,URNAJUSTOULTRICIESANTE,EGETMAXIMUSFELISLOREMNECNUNC.ETIAMINTERDUMAUGUEQUISLIGULALUCTUS,ATEMPUSFELISSOLLICITUDIN.MAECENASGRAVIDARUTRUMURNAINMOLLIS.SEDINULTRICESAUGUE.FUSCEUTAUGUEETORCIULTRICESPRETIUMEUVELENIM.ALIQUAMASAGITTISIPSUM.SUSPENDISSEBLANDIT,LOREMNECELEIFENDDICTUM,DUILIBEROFAUCIBUSLOREM,NONMOLLISNIBHEXEUNUNC.MAURISDIGNISSIMTEMPUSORCISEDVULPUTATE.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.MAURISCOMMODOFEUGIATMETUSVITAEDIGNISSIM.DONECPELLENTESQUERHONCUSPORTA.AEEANVOLUTPATMASSANONORCIMOLESTIE,EUHENDRERITVELITLAOREET.NAMATINCIDUNTLIBERO,INTINCIDUNTNUNC.ALIQUAMINTERDUMMAURISULLAMCORPER,POSUEREDOLORAC,INTERDUMLEO.AENEANATANTEMETUS.QUISQUEVENENATIS,METUSGRAVIDALUCTUSLOBORTIS,PURUSJUSTODAPIBUSERAT,ACFACILISISVELITARCUNECNISI.MORBIBLANDITPULVINARDIAM,QUISSAGITTISEROSTEMPORA.ETIAMCONSEQUATFEUGIATEROS,SUSCIPITSCELERISQUERISUS."; // Define um vetor de caracteres para armazenar o texto original
    char chave[20] = "PIZZA"; // Define a chave de criptografia

    while (inicio < 8000) { // Loop para processar o texto em partes de 500 caracteres
        int j = 0; // Variável para controlar o índice do buffer

        for (int i = 0; i < 500; i++) {

            char c = texto[inicio + i]; // Obtém o caractere do texto original

            if (c == '\0') { break; } // Verifica se é o final do vetor

            if(c != ' ') {  // Ignora os espaços
                buffer[j] = toupper(c); // Converte o caractere para maiúsculo e armazena
                j++;
            }
        }
        buffer[j] = '\0'; // Adiciona o caractere nulo ao final do buffer
        printf("%s", buffer); // Imprime o texto formatado
        inicio += 500; // Incrementa o início para processar a próxima parte do texto
    }
}

/**
 * Função: encriptar(). Esta função realiza a criptografia de um texto usando a cifra de Vigenère.
 * 
 * @param chave (char*): Uma string representando a chave de criptografia.
 * @param texto (char*): Uma string representando o texto a ser criptografado.

 * Comportamento:
 * A função percorre cada caractere do texto e aplica a cifra de Vigenère para criptografá-lo.
 * Para cada caractere do texto, a função determina a letra correspondente da chave.
 * Em seguida, para cada letra maiúscula do texto, ela aplica a seguinte operação:
 * Calcula o deslocamento somando o valor ASCII do caractere do texto com o valor ASCII da letra correspondente da chave.
 * Realiza o módulo 26 (o tamanho do alfabeto) para garantir que o deslocamento seja dentro do intervalo de letras do alfabeto.
 * Adiciona 65 ao resultado para garantir que o valor final esteja no intervalo das letras maiúsculas na tabela ASCII.
 *
 * Obs: Esta implementação assume que o texto contém apenas letras maiúsculas.
 *
 * Observações adicionais:
 * A função não retorna nenhum valor, pois ela altera diretamente a string do texto original passado por referência.
 * Se o texto contiver caracteres não alfabéticos ou minúsculas, eles não serão criptografados e permanecerão inalterados.
**/

void encriptar(char *chave, char* texto){
    int chaveLength = strlen(chave); // Obtém o comprimento da chave
    int textoLength = strlen(texto); // Obtém o comprimento do texto
  
    for (int i = 0; i < textoLength; i++) {
        char letraChave = chave[i % chaveLength]; // Obtém a letra da chave para a posição atual
        texto[i] = texto[i] > 64 ? (texto[i] + letraChave) % 26 + 65 : texto[i]; // Aplica a criptografia apenas a letras maiúsculas
    }
}

/**
 * Função: desencriptar(). Esta função realiza a descriptografia de um texto cifrado pela cifra de Vigenère.
 * 
 * @param chave (char*): Uma string representando a chave de criptografia.
 * @param texto (char*): Uma string representando o texto a ser criptografado.
 *
 * Comportamento:
 * A função percorre cada caractere do texto criptografado e desfaz a cifra de Vigenère para descriptografá-lo.
 * Para cada caractere do texto, a função determina a letra correspondente da chave.
 * Em seguida, para cada letra maiúscula do texto criptografado, ela aplica a seguinte operação para desfazer a criptografia:
 *  - Calcula o deslocamento subtraindo o valor ASCII do caractere do texto criptografado pelo valor ASCII da letra correspondente da chave.
 *  - Adiciona 26 ao resultado antes de realizar o módulo 26 para garantir um número positivo após a subtração.
 *  - Realiza o módulo 26 (o tamanho do alfabeto) para obter o deslocamento original.
 *  - Adiciona 65 ao resultado para garantir que o valor final esteja no intervalo das letras maiúsculas na tabela ASCII. 
 *
 * Obs: Esta implementação assume que o texto contém apenas letras maiúsculas e foi criptografado com a mesma chave usada na criptografia.
 * 
 * Observações adicionais:
 * A função não retorna nenhum valor, pois ela altera diretamente a string do texto original passado por referência.
 * Se o texto contiver caracteres não alfabéticos ou minúsculas, eles não serão descriptografados e permanecerão inalterados.
**/

void desencriptar(char *chave, char *texto){
    int chaveLength = strlen(chave); // Obtém o comprimento da chave
    int textoLength = strlen(texto); // Obtém o comprimento do texto
  
    for (int i = 0; i < textoLength; i++) {
        char letraChave = chave[i % chaveLength]; // Obtém a letra da chave para a posição atual
        texto[i] = texto[i] > 64 ? (texto[i] - letraChave + 26) % 26 + 65 : texto[i]; // Desfaz a criptografia apenas das letras maiúsculas
    }
}

/**
 * Função: wrapEncriptar(). Esta função é responsável por dividir um texto em partes de 500 caracteres e criptografar cada parte usando a cifra de Vigenère.
 * 
 * @param inicio (int): Um valor inteiro representando o início da posição no texto a ser processado.
 * @param buffer (char*): Um buffer de caracteres que armazena temporariamente partes do texto para serem criptografadas.
 * 
 * Comportamento:
 * A função percorre o texto em partes de 500 caracteres, a partir da posição 'inicio', armazenando cada parte em um buffer.
 * Para cada parte do texto, ela chama a função 'encriptar' para criptografar o conteúdo do buffer usando uma chave fixa ('PIZZA').
 * Após a criptografia, imprime a parte criptografada na porta serial.
 * 
 * Observações:
 * - O texto a ser processado está armazenado na variável 'texto', que é um array de caracteres de tamanho 8000, inicializado com uma string vazia.
 * - A chave utilizada para a criptografia é definida como "PIZZA".
 * - A função 'encriptar' é chamada para criptografar o conteúdo do buffer.
 * - A função não retorna nenhum valor, pois seu objetivo é imprimir as partes criptografadas na porta serial.
**/

void wrapEncriptar(int inicio, char *buffer) {
    char texto[8000] = "LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.QUISQUEETJUSTOAPURUSCONVALLISFEUGIATQUISNECQUAM.DONECSEDLOBORTISSEM.NAMELEIFENDJUSTOAVELITIACULISEFFICITUR.CRASSODALES,QUAMVITAEMOLLISALIQUAM,LIGULALEOINTERDUMEST,IDMAXIMUSAUGUEDOLORSEDLIBERO.MORBIEUMAURISLECTUS.CURABITURSITAMETMAGNASOLLICITUDIN,LACINIALIBEROINTERDUM,MOLESTIEVELIT.DONECPORTTITORIDSAPIENINULTRICES.SEDQUISQUAMSITAMETANTEULTRICIESINTERDUMQUISQUISURNA.PRAESENTEUISMODLOBORTISNIBHSEDFACILISIS.ETIAMMATTISMAURISSEM,ACPOSUERENEQUEBIBENDUMEU.VESTIBULUMSODALESEFFICITURQUAM,NONACCUMSANFELIS.VIVAMUSETAUGUEINLEOAUCTORFAUCIBUSETELEMENTUMENIM.DONECTRISTIQUEFRINGILLANEQUE,VELELEIFENDNISIAUCTORID.ETIAMVELNUNCETLACUSRUTRUMVIVERRA.SUSPENDISSEPELLENTESQUELOREMIDMASSARHONCUS,NONALIQUETODIOLAOREET.PRAESENTUTVEHICULAARCU.PROINEGETMOLLISMASSA,VELCONSECTETUREX.PROINANTEMI,ALIQUETSITAMETTEMPUSNEC,DICTUMTEMPUSODIO.SEDAUGUEEST,CONDIMENTUMACALIQUAMEGET,CURSUSAJUSTO.INTEGERGRAVIDAANTEMAGNA,NECCONDIMENTUMLOREMFEUGIATET.DONECEGESTASPELLENTESQUEMOLLIS.PELLENTESQUEETELITIDSEMPOSUERECONSECTETURUTETURNA.AENEANPLACERATFACILISISTORTOR,IDPORTTITORDOLORCONGUEUT.NUNCBLANDITPULVINARVELIT,FEUGIATMATTISNULLAFAUCIBUSSED.UTNONNISLEGETNISIPLACERATDICTUMQUISEUTURPIS.VIVAMUSUTSODALESNUNC,ACSOLLICITUDINODIO.INTEGERSEDNIBHCURSUS,PLACERATANTEAC,IMPERDIETPURUS.PROINEGESTASAUGUEVELSAPIENVESTIBULUM,EUIACULISEXMOLESTIE.MAECENASIDRISUSULTRICIES,PLACERATODIOA,PORTAARCU.ETIAMATLOREMRHONCUS,IACULISESTAT,DIGNISSIMLIBERO.PELLENTESQUEDAPIBUSPULVINARLACINIA.PRAESENTBIBENDUM,NEQUEQUISULTRICIESLAOREET,LACUSEXTRISTIQUEDIAM,NONCURSUSEXDOLORINTORTOR.FUSCELACUSEST,ULTRICESMALESUADACONGUEEGET,SODALESINTURPIS.NULLAMEGETNISIACRISUSEUISMODLAOREET.SUSPENDISSEETALIQUAMVELIT.UTSODALESLOBORTISRISUSCURSUSDICTUM.PHASELLUSEUMOLESTIEIPSUM,IDRUTRUMLECTUS.PRAESENTCURSUSCOMMODOERATSEDHENDRERIT.CURABITURVIVERRATELLUSVITAELACUSAUCTOREUISMOD.PRAESENTEGETSEMNULLA.PELLENTESQUEACELITMASSA.NAMARISUSNIBH.PELLENTESQUEACCUMSANNIBHVELPORTTITORVARIUS.SEDELEMENTUMELEMENTUMDUIVELELEIFEND.CRASPLACERATSAPIENVELNISITINCIDUNT,VITAETINCIDUNTLOREMPRETIUM.INELEMENTUMDUIUTDICTUMHENDRERIT.DONECGRAVIDAQUISTELLUSIDDICTUM.MAECENASNECQUAMNISI.MAECENASTURPISSAPIEN,LUCTUSACSAPIENET,VIVERRAPHARETRAMETUS.VIVAMUSCONDIMENTUMARCUIDCOMMODOCOMMODO.VESTIBULUMTINCIDUNTTURPISEUARCUVENENATIS,EGETTRISTIQUENISILAOREET.PRAESENTTINCIDUNT,EROSVELSOLLICITUDINLUCTUS,MASSASEMDIGNISSIMNISI,SEDLUCTUSLIBERONISIETAUGUE.SEDEGETMOLLISEX.NULLAAESTNECNISIPULVINARRHONCUSIDVITAEEX.PROINVITAEEUISMODMI.FUSCEVITAESODALESTURPIS.VIVAMUSSODALESENIMEGETVOLUTPATLAOREET.INTEGERSITAMETORCIETANTELOBORTISFAUCIBUSSITAMETNONEROS.NAMVARIUSNECNIBHNECSEMPER.DUISIMPERDIETERATETPULVINARDIGNISSIM.NUNCFINIBUSSEDMIQUISVOLUTPAT.FUSCEFAUCIBUSULLAMCORPERGRAVIDA.INPOSUERETEMPORRUTRUM.NUNCDAPIBUSTORTORACPELLENTESQUECONDIMENTUM.FUSCESOLLICITUDINULTRICESLIGULANECINTERDUM.ETIAMAVIVERRAPURUS,VITAERUTRUMIPSUM.SUSPENDISSEPOTENTI.DONECPOSUERECONVALLISNISIUTALIQUET.FUSCESODALESNISIINFELISPRETIUMTINCIDUNT.VESTIBULUMSITAMETMOLLISNEQUE,EGETMALESUADAORCI.MAECENASPULVINARENIMVITAEDOLORTEMPUSMATTIS.INTEGERVITAEFELISLECTUS.NULLAORCIEROS,FEUGIATAULLAMCORPEREGET,ALIQUAMSEDAUGUE.NULLAMSEDULTRICIESMETUS.PELLENTESQUEVITAEAUGUESITAMETDOLORVESTIBULUMCOMMODO.VIVAMUSTINCIDUNTDOLORLIBERO,VELSODALESSEMHENDRERITIN.SUSPENDISSELOBORTISCURSUSSEMPER.CURABITURDICTUMCONSECTETURBIBENDUM.MAECENASCONSECTETURIDVELITINPHARETRA.PELLENTESQUECOMMODOVOLUTPATMAGNA,INULTRICESENIMLACINIAPLACERAT.NULLAMSEDANTEAANTEPELLENTESQUEMOLESTIEETSEDAUGUE.PELLENTESQUEDIGNISSIMSOLLICITUDINPURUSIDDAPIBUS.PELLENTESQUEACACCUMSANERAT.PROINACMETUSNONPURUSFEUGIATVESTIBULUMSEDSITAMETELIT.PHASELLUSHENDRERITULTRICIESMAGNAEUSODALES.PELLENTESQUEHABITANTMORBITRISTIQUESENECTUSETNETUSETMALESUADAFAMESACTURPISEGESTAS.CRASFRINGILLACONSECTETURRISUS,INRUTRUMNISIFRINGILLAET.CLASSAPTENTTACITISOCIOSQUADLITORATORQUENTPERCONUBIANOSTRA,PERINCEPTOSHIMENAEOS.FUSCENECCONGUENISI.FUSCETINCIDUNT,QUAMINEGESTASMAXIMUS,TURPISMASSAMOLLISLECTUS,ETBIBENDUMDIAMSAPIENIDLOREM.DONECETEXVELIT.DONECCURSUSSEMIDDICTUMTINCIDUNT.MORBIACCUMSANQUISLOREMETDICTUM.DONECFACILISISCOMMODONEQUEUTPORTTITOR.PHASELLUSQUISRISUSINANTEFEUGIATBLANDITUTNECRISUS.DONECALIQUAMNIBHLIBERO,EGETVESTIBULUMNULLAMAXIMUSVEL.INTEGERVELITSEM,DIGNISSIMUTPLACERATAT,PORTAEGETANTE.DUISEGETTURPISSEM.QUISQUEFINIBUSULTRICIESDUIACAUCTOR.PROINVELTORTORPHARETRA,MALESUADAMAGNAPRETIUM,MATTISERAT.PHASELLUSMOLESTIETELLUSPORTTITORLIBEROPOSUERERUTRUM.PRAESENTPHARETRAMETUSVITAELOREMCONVALLISBIBENDUM.PRAESENTPHARETRAORCIEGETFACILISISMATTIS.DONECPELLENTESQUENUNCIDEROSVEHICULAIACULIS.DONECETTELLUSIDLOREMEGESTASRHONCUS.SEDERATNEQUE,RUTRUMETEROSEU,SODALESULTRICIESNEQUE.VESTIBULUMIDMASSAVARIUS,CONSECTETURTELLUSQUIS,HENDRERITNULLA.DUISVELTEMPUSSEM.ALIQUAMERATVOLUTPAT.PROINBLANDITALIQUAMELITVITAEFERMENTUM.NAMACNULLAIDTURPISTINCIDUNTEFFICITUREGESTASVITAEDIAM.CURABITUREGETCONDIMENTUMLIBERO,NECCONGUEMETUS.SEDTINCIDUNTATMAURISNONALIQUAM.PHASELLUSEFFICITURARCUSITAMETSODALESPHARETRA.VIVAMUSEUENIMDICTUMNUNCIACULISMAXIMUS.CRASLUCTUSALIQUAMNEQUEVITAECONSEQUAT.VIVAMUSUTMASSAORCI.INHACHABITASSEPLATEADICTUMST.INSAGITTISNEQUEACIACULISULLAMCORPER.AENEANBIBENDUMQUAMSITAMETARCUTEMPUSEUISMOD.ALIQUAMSUSCIPITELITCURSUSVIVERRATRISTIQUE.NAMMAXIMUSSEMATVELITULTRICES,NONCOMMODOMASSAPELLENTESQUE.NULLAELITNIBH,CONSEQUATNONLEOVEL,PULVINARAUCTORLACUS.MAURISCONVALLISVITAEJUSTOTRISTIQUEEUISMOD.DONECALIQUETALIQUAMLIGULA,AMOLESTIEDUIRUTRUMAT.NAMBLANDIT,ELITNECGRAVIDARUTRUM,NIBHSAPIENALIQUETDUI,VITAEFAUCIBUSLIBEROENIMETODIO.PRAESENTCOMMODOORCIFERMENTUMLECTUSMOLLISTEMPOR.SUSPENDISSESUSCIPITVELITSITAMETSUSCIPITGRAVIDA.PHASELLUSSEDMASSAEUMAGNAPHARETRATRISTIQUESEDUTVELIT.MAURISQUISPRETIUMRISUS,IMPERDIETALIQUAMLECTUS.UTRUTRUMDOLORMAGNA,VITAECONSEQUATDOLORCURSUSNON.SUSPENDISSETINCIDUNTDAPIBUSLOBORTIS.PRAESENTAAUCTORTURPIS,VITAELOBORTISELIT.DONECFAUCIBUSLECTUSAFAUCIBUSORNARE.SEDVELMETUSDAPIBUSEXPHARETRAFRINGILLA.NUNCUTFELISGRAVIDA,CONVALLISEXSED,MOLESTIETORTOR.PELLENTESQUEDIGNISSIMLECTUSVITAEORCISUSCIPIT,VENENATISPORTTITORSEMTEMPUS.QUISQUESITAMETSAGITTISENIM.ALIQUAMSITAMETORCIINQUAMFRINGILLAALIQUAM.DONECAUCTORVEHICULATINCIDUNT.CRASTRISTIQUEELITEUQUAMLACINIAORNARE.SEDINFINIBUSLACUS.SUSPENDISSEEUIPSUMNECMAGNAPORTTITOREUISMOD.VIVAMUSULLAMCORPERMATTISALIQUET.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.SEDMALESUADAQUISRISUSIDEFFICITUR.FUSCEVITAELACUSELIT.DONECEUISMODENIMNONAUCTORPULVINAR.FUSCEVIVERRAACCUMSANNULLA.VIVAMUSCONDIMENTUMMOLESTIEJUSTOUTALIQUET.QUISQUEDIGNISSIMPORTAFACILISIS.NULLAMEUISMOD,LECTUSUTELEIFENDSAGITTIS,ODIORISUSELEMENTUMQUAM,EGETSUSCIPITFELISELITQUISNISI.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.INULTRICIESTORTORVELHENDRERITDICTUM.VESTIBULUMVIVERRAVIVERRAIMPERDIET.UTEFFICITURESTNONANTESODALES,SITAMETTEMPORLECTUSULTRICES.SEDHENDRERITVIVERRASAPIENEULACINIA.QUISQUELOREMNISI,MATTISSEDVEHICULAID,LOBORTISACURNA.PRAESENTCONVALLISJUSTOVIVERRAEXVOLUTPATTEMPUS.MAURISCONVALLISEUISMODNIBH,SITAMETSOLLICITUDINENIMPHARETRAAC.DONECLACINIAGRAVIDAMETUS.MAURISQUISPELLENTESQUETURPIS.PELLENTESQUERUTRUM,SEMNECRUTRUMAUCTOR,TELLUSPURUSPORTASEM,ACFACILISISMAURISURNANECAUGUE.NULLAMETFAUCIBUSEX,EGETULTRICIESSEM.NULLAMVENENATISEROSLOREM,VIVERRAULTRICIESDOLORMALESUADAIN.DONECNECTORTORTELLUS.UTVIVERRA,EROSNECFAUCIBUSLACINIA,URNAJUSTOULTRICIESANTE,EGETMAXIMUSFELISLOREMNECNUNC.ETIAMINTERDUMAUGUEQUISLIGULALUCTUS,ATEMPUSFELISSOLLICITUDIN.MAECENASGRAVIDARUTRUMURNAINMOLLIS.SEDINULTRICESAUGUE.FUSCEUTAUGUEETORCIULTRICESPRETIUMEUVELENIM.ALIQUAMASAGITTISIPSUM.SUSPENDISSEBLANDIT,LOREMNECELEIFENDDICTUM,DUILIBEROFAUCIBUSLOREM,NONMOLLISNIBHEXEUNUNC.MAURISDIGNISSIMTEMPUSORCISEDVULPUTATE.LOREMIPSUMDOLORSITAMET,CONSECTETURADIPISCINGELIT.MAURISCOMMODOFEUGIATMETUSVITAEDIGNISSIM.DONECPELLENTESQUERHONCUSPORTA.AEEANVOLUTPATMASSANONORCIMOLESTIE,EUHENDRERITVELITLAOREET.NAMATINCIDUNTLIBERO,INTINCIDUNTNUNC.ALIQUAMINTERDUMMAURISULLAMCORPER,POSUEREDOLORAC,INTERDUMLEO.AENEANATANTEMETUS.QUISQUEVENENATIS,METUSGRAVIDALUCTUSLOBORTIS,PURUSJUSTODAPIBUSERAT,ACFACILISISVELITARCUNECNISI.MORBIBLANDITPULVINARDIAM,QUISSAGITTISEROSTEMPORA.ETIAMCONSEQUATFEUGIATEROS,SUSCIPITSCELERISQUERISUS."; // Define um vetor de caracteres para armazenar o texto original
    char chave[20] = "PIZZA"; // Define a chave de criptografia

    while (inicio < 8000) { // Loop para processar o texto em partes de 500 caracteres
        int j = 0; // Variável para controlar o índice do buffer

        for (int i = 0; i < 500; i++) {
            char c = texto[inicio + i]; // Obtém o caractere do texto original
            if (c == '\0') { break; } // Verifica se é o final do vetor
      
        buffer[i] = c; // Armazena o caractere no buffer

        }
        encriptar(chave, buffer); // Chama a função para encriptar o texto no buffer
        printf("%s", buffer); // Imprime o texto encriptado na porta serial
        inicio += 500; // Incrementa o início para processar a próxima parte do texto
    }
}

/**
 * Função: wrapDesencriptar(). Esta função é responsável por dividir um texto criptografado em partes de 500 caracteres e descriptografar cada parte usando a cifra de Vigenère.
 * 
 * @param inicio (int): Um valor inteiro representando o início da posição no texto criptografado a ser processado.
 * @param buffer (char*): Um buffer de caracteres que armazena temporariamente partes do texto criptografado para serem descriptografadas.
 * 
 * Comportamento:
 * A função percorre o texto criptografado em partes de 500 caracteres, a partir da posição 'inicio', armazenando cada parte em um buffer.
 * Para cada parte do texto criptografado, ela chama a função 'desencriptar' para descriptografar o conteúdo do buffer usando uma chave fixa ('PIZZA').
 * Após a descriptografia, imprime a parte descriptografada na porta serial.
 * 
 * Observações:
 * - O texto descriptografado será armazenado na variável 'textoDes', que é um array de caracteres de tamanho 8000.
 * - A chave utilizada para a descriptografia é definida como "PIZZA".
 * - A função 'desencriptar' é chamada para descriptografar o conteúdo do buffer.
 * - A função não retorna nenhum valor, pois seu objetivo é imprimir as partes descriptografadas na porta serial.
**/

void wrapDesencriptar(int inicio, char *buffer) {
    char textoDes[8000] = "AWQDMXXRTMSWKNRHQSZMTB,BOCADBTTBTQASQOHSRQMFEAQS.QJQRPUTMSIUHBNZPJZTRCDVUZLAQREEJOHZTFCHRNTKPTAB.CNNTKRDDAWANRIQRREB.MZMTTDHFTVCIUHBNZVTTHSIPKTKIHMEEIRQSTR.KQZSHWCZLTA,PUPUUHTPMLNLAQRZLXYTZM,THFUAIKDOXVSDRSCLDSI,HCMPFHLUHITFUTLNKOGADCLXJDQO.UNQBXMTLAJZHRLTKSTS.KTQAQQSTRHQSZMTBLZGCIRNLAQBHTJLHM,AIBHNXIKHBTZNHNIMQCUB,LNLTASHEKMKHT.LNMERXNQTIQSNRXLRZPXMMHNJTSQIRMR.STLPTIHYTZMHQSZMTBZMTTCKSRXKHDSXVSDRSCLPUXAPTIHCQMA.XQZEHMMSEJQRLOSTNAOGBHRNXJGRESNZBIAQRHS.MSHABUZSTXALZUGQRREB,ZBPDATDRTVDPUTJHAECLTLEJ.UDSIQATLJURNDPTDREUNHBIICQPUPU,MOCIBBUBAZMFTTHR.KQUZMJADSAJOTDICTDNAJKSNRUITBIQCRDTTTDLECBTLECQL.DDVDBTGQRSIFCDERXVFHLAIMDQJM,UEAMKDIUMMCNXAHZURBNQIS.DSIPUUDLCCMBEITZBUHZTSRJUUHVTZQZ.HCROECLHRSTXDKLTVSDSFCDKOGMLHDBIRRAGPNMCJA,MOCIKHQJMSNDXWKZOGMDS.EZZDSTVSTTKMGHCJTZZRRC.ORDQMDGTBLNLAQRLAHAZ,VTTBNNHMBSEICQDX.XQNICIMSEBQ,ZLXYTDTHQSZMTBSDMECRMER,CHCICLSEBXTROSQN.STLZTGJMDRT,KNMDXUDMTJUZBAAQPTABMFDT,KTQSJAZIUHBN.ICBDFEGOQZVXLZZNIMLZGCI,MERKNMDXUDMTJUKNRTUEDUVQZSEI.CNNTKDFEHBZRPTTKDNIMRPUTUNKLXA.OEATDMTTAPTETBDKIIQCREBXNRUTZDBOCADBTTBTQUIMSTRCI.ZECMZMPAIBDRPBEZCXTHRIHBNQTDZ,HDEWQSTXBNQDDTNQCDVFTEJB.MUCKAKACLHSPJTUHNPZUDLXB,EEJOHZTBISSIHVTKLPNZTCXJTRSTL.TTCWMMIHTDFEIVHRIETZBEGISCIRBTLQJQRDUICQOIH.UHVPUTRUIANCAAMRMUCK,ZCHWKKIRQSTDXVNCID.HMTTODQSTLMHBWKTQSJA,OLPKDQAIIMSEPK,HMEMQCITBOTRJA.ORDQMDGTASZSPCFTEKMKRAEQDMVTASHBJTTL,TCHZCJTHREMUNKEHBHD.BIDBECIRHDGQRTSJTSQIRQDR,ETZBEGISNDXWZ,PDZSZAGKT.EIQZLAITNQEBZGNNRCR,IPKTKIHMRSAI,CHGCQRRIBTHAEGW.OEATDMTTAPTESIOHBJAOTLKQMZRAIBHNXI.ORPMRDNIJHAECLTL,CMPTEFCHRUABQHCXMRKADZDDT,TZBUHMWSRXASHQJMCHAB,MNNRCQRUHMWCOAWQHNIWQSOG.ETSRMKZCJADRT,CKSRXKDRMPTDRUPLZBOCOTDEVMS,SDLZKEHQMSUGXHR.CCKKABMFDTCQRHARZHRUHMTHSBWCKADZDDT.ATRPTVCHSHMDSAAQPTABDDKII.TSSDLZKEHTNAOGBHRRXATRCJZRTSSQBSUB.OGAHMKKUHMTLOAMRSITQORUB,HCRJBQTMAMBSUH.OQATADMTRCQRUHKNLMDLNDRPBRDDWMMCRTZHS.RCQZBXBTQVXDDQRPBDKLJAUHTPMKZCJAZTCIWQDUXALND.XQZEHMMSEVMSREBVTKLP.ODLAMMSEHYTDARMKHTBIRRA.VZLAGQRTSCQAG.EMKKECBDRQJMZBCJURZNCQAGVTTONRIBHSOGDZQIJA.RESMKDMTVSTMTTDLECBTLDJQUDLTTDHFTVC.CGIROLPKDQAIAZOITVUDLCQRHTXVBHDJVS,VXBZDTXVBHDJVSKOGMLORTBHTM.QMDLTUDMTJUCTIJBCHCICLGECLQDRXB.COCMBFRPDHCAFCHRTTTKTSXLCHCICL.MPMBDNPAMDCFCZLNXAH.MPMBDNPASTREQRRAEQDM,ACBSUHIBRAEQDMEI,UHVTZQZPWIQDTGILDTJA.UIKILTSRWMCIBMMSUBIQBUXLBNMBWCNCDULNDD.UDSIQATLJUSHNRQCTNIBTQPXADTAGKTUECMMZTXA,DGTBSQIHBHPUTVHRIAINQETB.ORPMRDNIBHMCXLTMT,MQNSKMKROATHBIICCHNACBSUH,LZSHIRDMSQFMIHAHLNXAH,STLKTCICRKIQMQNNXAHDTPCFTE.ADCEVMSLOATHREM.MTLAIZDSIVDBNXAHOUADHMAGZGNNRCRHDKQSZETF.ORDQMUIIIDDUXALNDBQ.EUHKDUIIIDROSIKDSICQOIH.UHVPUTRSDLZKEHMMHMTODSVDTTSPPBKZOGMDS.XVSDGTZRHTPUDSOGKHDTPVSDLDJNQTXAEZURQATSHQSZMTBMNNTZNR.CILUAGQTRNTKMHBWVDBSTUODR.LTHSXUODRSQDSEGISDTECKUICIQCIVVHRSXU.MUCKEHNXJTRSTLLHQJQRUOACSOAI.ETSRMEZURQATSJTKZMRWQOEGOQZVXLZ.ICXNRUTZDSEBXNQRJBQTM.VTMCSIOHBJASNRIWQZCEMKKECBDRQJMBNNSQLDNICL.FJABDSDTKHCXBTCICCKSRXKDRLXOTKACMBHNIMQCUB.DSIPUZUIKMQQAECQTS,DHSATZTSRJUHOSJU.RUHXDMDXARDPDBDMTX.CNNTKONSJMQDCDVUZLAQRMIHQTSAAQPTEI.ETSRMRNDPTDRNXAHHNUMKHSEZDSIJUSHNRQCTNI.UDSIQATLJURHTPUDSMDTKHSCMPTE,MFDTBIKDSJICZOGKH.MPMBDNPAOTLKQMZRTVHLVXBZDDDTNQTTUOTSBISSIH.HMTTODQVXBZDFTTHRLTKSTS.VTKLPWQBITZNR,UMTFIPBZTLAILBOGXDQEVMS,AAQPTABADCAJOTD.CCKKABADCUABQHCXMRLEICR.PTTKDNIMRPUTDHSATITFUTAHSABMSCOAWQUEHBHAUACLBOBUNCO.DHUABCRSICKHCUCBCNLDZKHBTZN,VTTRNDPTDRSTUGDNSZDQIIQM.SJAODNSQRREAWANRIQRBUGATRSTUODR.KTQAQQSTRSQBSUBKNMSTKSDTJZAHBTVCTM.UZDCTVZRCDVRDCIMSTRXLUDLXBHMPWIQDTGI.OEATDMTTAPTERWLLOSWUNLJBOZTBIFMA,QMTLIZHBEHMMHMAIBHNXIOKARMQZT.VTKLPURDDPVSDAPVSDPTTKDNIMRPUTUNKEHBHDEIADCAJOTD.EMKKECBDRQJMCHGCQRRIBANKLXKHSUSQMOUGCRHDSIOHBJA.OEATDMTTAPTEPKZBCJURZNTZZS.EZNHNPKLDTJAMNNECQTSUMTFIPBUDSIQATLJURDDHQSZMTBDKII.OGAHMKKUHPDMDGMQHTJTSQIRQDRMPOMZEJANCAAMR.PTTKDNIMRPUTPZAIIIMSMDZAHTGQRSIFCDRECMBSUHMSMEICRDTBIKDSJICZFPUDRARBTQPXADFEHBZR.RZZRFGQMFIATZBOCADBTTBTQRXATR,XVQTTGCLMIHQEQICOHKLPMS.CAIRRAEBDMTIIBHTXANBIDAPTASTHSOGISNRFCDMTEMQBOCCAHACWRSRP,ODRXVBDPIWRGIBMMZEDA.EUHKDMERKNMGJMMHSX.ETSRMSHNRQCTNI,PTABQMDGTASZSBIWHMJA,SUGXHRMPARZMDTKHSAMBSUH,DSBXJDMDJUCHABAZOITVHCLDZDL.SWMDCTBDWVTTHS.SWMDCRCQRUHADLISLHBTJUSHNRQCTNI.LNRQQZBCJURZNFCHRLDZDLEILHBTJU.COCMBEARQKHSXABNMBWCNNTYTDUIXNQTIQSNR.XGZSTTKTSFCHRRXATRICIMSEUMTFIPBAKACLHSUIVDBRXATR.SWMDCPTHPUPUMHBWTHAEGW,DGTBUDSIQATLJUMTLAILZXXUTRVTT.HNIMFDRKMKHTHML,DXOMHSHQLTTETZBEGISZT,XNQTPMFDTPVSD.SCHREVMSSUGXHRSTU.PUXAPTEUQMHBJATKTGQBHEHLTHARITBTDZ.ORDQMUEABNQTDZOGAGMSQA,UZKEHCZCABIFMAEZDSIJU,LAIBHREGIS.PWIRDLACRLOAMRSITBDKLJAONRIBHSOGTHAEGWONSJMQDRJBQTM.XQZEHMMSPWIQDTGILDTJAUHTPMKNRTUBNNKIKKIHJHAECLTL.EZZDSTVSOHPZDSRPWQBITODSFPKHKIHQRLAIBHR.SWMDCEMKKECBDRQJMMTNRQCDRDAUDHXKTKAXIBTLXA.COCMBDTIMKKUHQCKOGMLDGTASZSGPNMCJA.RESMQZTCMPTE,ZTSRJUDSEGWRDU,ANCAAMRTLIZHBITAMDQJM.UEHBHAUACLHDBIRRAKIQHUH,BNNHMBSEICQSEATTRQJQR,HTVCQEGQSMUATZ.DJQRUEABDLPJARDM.IKHQJILDRPBUNLJBOZT.XQNICJKZNSQSZLXYTZMTTHSVXBZDFTZLDNICL.NPUZBNJTKZISBTQPXASHNRQCTNIMEEIRQSTRTODRTPAUHTPMCHAB.BTRPJHSUGMFDTRWMCIBMMSUBTHAEGW,MERKNMGJMLDTJA.RESBHMCXLTMTPBLZUGQRMOCIKHQJIL.PWIRDLACRDFUQBHTJZZQCJAHSABMSROSIKDSEPZQEIZZ.VXDZLUHMTDNXUCHCICLMUCKHZCJTHRMPFHLUH.BQAHTTBTJAZKIFCZLNTYTDVXBZDCDVRDQJIS.VXDZLUHCSLAHAZNRRQ.HNWIBGAQQSZSHMOKAIMZCIRBTLSI.HMSPOHSTXAMDQJMZBIPKTKIHCKKABKNQPTZ.ZECMZMBXJDMDJUPTABAHSABMSZRRCSDMECRDUXALND.IKHQJILRUHKHOIIMKHTRCQRUHDHUEGZZSRXASHQJM.MABUZWIBCRREBISUEAQSTLIZHBEH,MNNRWLLOSWLZSHIODLAMMSEHYTD.CCKKATTHSNXJG,CDVRDQJISMOCTDNVTT,OUADHMAGITBTDZKZCJA.LAJZHRCDVUZLAQRUIIIDIUHBNSRXASHQJMDTIHUNC.SWMDCPTHPUTBZKIFCZLLXOTKA,ILNLTASHESCHQUIZTLAI.MZMQTZMDXB,DLXBMDCVZZUISIQTTGCL,NXJGRAEQDMAAQPTEILTH,KQSZEUITBIQCRKIQMQNECQLDTDLHN.EZZDSTVSBOBUNCODZBHFTZLDNICLKERBTRMDTKHSIMLOOG.RTSEMMCIHADRUHKHOIIDDKIIAHSABMSRUHKHOIIOQZVXLZ.PWIRDLACRRESUZRSPMTLAVVZOHPZDSRPBQHSIQPTEHMCTTKMKHT.UZTRXAPTIHXQDTXCLQIHCR,IBXDQDXMSZLXYTZMAMBSUH.TSRJBQTMSWKNRBIFMA,DHSATKNMSTYTZTSWKNRRCQRUHVNM.HCROECLHRSTBHMCXLTMTSIOHBJAKNBDZSHS.XQZEHMMSAPCBSOGBTQPXA,UIIIDKOQWQSIHMKHT.LNMERNZTCXJTRLTKSTSPNZTCXJTROGVZQE.ADCVTTLDTJACZPXJTREMXGZRTBQZFGQMFIATZ.NJVBTTUMKHSVZZUISI,BOCDZKLXADWSTL,LOAMRSITBNQTDZ.OEATDMTTAPTESQFMIHAHLLTKSTSKQSZEDZBHSJABHPXB,UECMMZTXAONRIBHSOGADLTTUOTS.YTHSFCDRIIILDTHIFHTIQRDNXU.ZLXYTZMHQSZMTBNQCXQMPUPUEQICOHKLPIKHQJIL.DDVDBAJKSNRKMGHCJTZSICKHCUCB.BRPASQIHBHPUTMKHTTCPTABTZBICQZNRCIQD.HMCHNUQMHBJAKZCJA.RUHXDMDXARDEJQORUBVDBMPOMZPDZSSIIWQDUXALND.DHUABCRTLAILBOGXDQMPBSHSPTHPUTB.KOGMLHPHCLCOAWQRIIILDT,KNMSTKSDTJZZCIEQRBICODKII.RDDBIKDSJICZQJQRQIHCRHDTNEHCXBTQ.UCRBEKQSZEAIBTSTTHS.SWMDCTCHRMDLDMIBVNMAJKSNRECKUICIQ.FJABDVXDDQRPIBBUBAZMNJTKZ.KQUZMJABNNSQLDNICLLOAMRSITRTRTDCSZLXYTDT.YTHSFCDCIVVHRSXUONRIIEZCXTHRIH.MTLAILDUXALND,TDBTJATSEAMHEECLRZGXBSHS,WCHOGQRTSTTDLECBTLQJIL,EVMSRUHKHOIINDKIHMKHTFCHRNXAH.LDZDLIEATLDDTNQSXBZLEI,BNNHMBSEICQZDXXHRCXVFDLXB.HNJTSQIRQDRTDZSNRKMKGECLQDRXBCHCICL.VTASHBJTTLVXDDQRPDHUEGZZHMEMQCITB.TTTNEHCXBTQEHBMNNPVSDSDLZKEH,RHTPUDSTTUONRAMBSUHCKSRXKDR.HMCGECLQDRXBUHVTZQZSPXHDNTCKZCXVHZ.FCHRQJMKNRTUMHSX,LZTIQRRESDDGIRCKZIS,KNBDZSHSPKTQNP.OQATADMTRWMUAATHRJJASNVXDDQRPMWUOACSOAIBDLPJA.LAJZHRCDVUZLAQRDUXALNDCQAG,HQSZMTBRNLAQBHTJLHMECQLOHPZDSRPIB.DDVDBLPKHMIPOQZVXLZLEICR.MPCQHSFCHRPTTKDNIMRPUTBTQPXA.OEATDMTTAPTEGCSQUB,RDMCMBQUIZTLAJKSNR,BDKLJAOTRJAONRIIRDM,IBEARQKHSXALZUGQRTRCIMDCPCFTE.VTKLPUDSFPCBHBJADW,TODSUABQHCXMRREB.MTLAILUECMMZTXADQOHTNQEB,UHVTZQZUABQHCXMRCOAWQLAAMRTASIHM.SWMDCCMBSOGBNQTTTKTS.CSUIKMQQA,MQNSCMBEAJKHAUHTZBICQZ,UGVZIUHBNTLIZHBITAZMTT,DFEIUZWIBCREEAQRKOGMLMERVTMC.MSHABQMSEGLTLAJOTDQJQRKIVCKZLJKSTS,ISDMECREEAQRROATHBIICCHN.UZDCTVZRGGIUHDPZTSRJUTQNPQMLOATHR.HMCHNJTSQIRMRZUVCD.FJABDUIITFUTMSNRRQTKTGQBDSEZDSIJUDTVTTDMIB.ZKIFCZLAHIFHTIQRHPHCL.SJAODNSQRREQTZMDXB,KOGMLMERMKDIUMMCDXKSTM,LTHLXJDQOUITBIQCRKOGML,NDVLNLAQRMIQPDWEJVTMC.UZTRXACHGCQRRIBBDLPJANQCXADCVJTOTTPBD.LDZDLIEATLDDTNQSXBZLEI,BNNHMBSEICQZDXXHRCXVFDLXB.LAJZHRCDULNDDNDTGXISLEICRUIIIDCIVVHRSXU.COCMBOEATDMTTAPTEGPNMCJAONRII.ZETIMUOACSOAIUZRSPVNMOGKHLOAMRSIT,DTHTVCQEGQSUEAQSKADZDDT.VZLAIQMBISCMSLXJDQO,QMSICKHCUCBMTNR.ZKIFCZLICBDQDJULZUGQRTLAILBOGXDQ,EWRTEGMCNLDZZB,XVSDRSCLKED.ZDNTIMZTPVSDMTBTR.FCHRQJMUDNTVZSIH,LDTJAFQAKQCZLJKSTSAWANRIQR,PJZTRJJASNDPXHAUHMQZT,IBEARQKHSXAUDLXBZQCJVDBNXAH.MDZAHBAIMCIIXTKVXVZQDXIL,QJQRRAVQSSIHMQNSIMLOOGI.DTXILBOCADPUPBEDUVQZSEGWR,SJABHPXBRBEAMQHSFCDQIHCR."; // Define um vetor de caracteres para armazenar o texto desencriptado
    char chave[20] = "PIZZA"; // Define a chave de descriptografia

    while (inicio < 8000) { // Loop para processar o texto desencriptado em partes de 500 caracteres
        for (int i = 0; i < 500; i++) {

            char c = textoDes[inicio + i]; // Obtém o caractere do texto desencriptado
            if (c == '\0') { break; } // Verifica se é o final do vetor
            buffer[i] = c; // Armazena o caractere no buffer
        }
        desencriptar(chave, buffer); // Chama a função para desencriptar o texto no buffer
        printf("%s", buffer); // Imprime o texto desencriptado
        inicio += 500; // Incrementa o início para processar a próxima parte do texto
    }
}

/**
 * Função: esvaziarMem(). Esta função é responsável por preencher um vetor de caracteres com espaços, limpando potencialmente a memória.
 * 
 * Comportamento:
 * A função define um vetor de caracteres 'c' com um tamanho de 8000 elementos.
 * Em seguida, ela percorre o vetor e preenche cada posição com o caractere de espaço ' '.
 * Este procedimento pode ser usado para "esvaziar" ou limpar a memória, preenchendo o vetor com espaços.
 * 
 * Observações:
 * - A função não retorna nenhum valor.
 * - O vetor 'c' é definido localmente dentro da função e é descartado quando a função termina, não afetando outras partes do programa.
 * - Esta função é utilizada para limpar o espaço de memória entre as operações de wrapEncriptar() e wrapDesencriptar(), garantindo que não seja imprimido lixo na porta serial.
**/

void esvaziarMem(){
    char c[8000]; // Define um vetor de caracteres
    for (int i = 0; i <= 8000; i++) { c[i] = ' '; } // Loop para preencher o vetor com espaços
}

int main() {

    int inicio = 0; // Início da parte
    char buffer[501]; // Buffer para armazenar partes do texto (+1 para o caractere nulo)
    buffer[500] = '\0'; // Garanta que a string seja terminada corretamente

    printf("Texto inicial formatado: \n");
    exibirTextoOriginalFormatado(inicio, buffer); // Chama a função para exibir o texto original formatado
  
    printf("\n");

    printf("Texto encriptado: \n");
    wrapEncriptar(inicio, buffer); // Chama a função para encriptar e exibir o texto encriptado
    esvaziarMem(); // Limpa a memória para tirar lixos na hora de imprimir na porta serial

    printf("\n");

    printf("Texto desencriptado: \n");
    wrapDesencriptar(inicio, buffer); // Chama a função para desencriptar e exibir o texto desencriptado
    return 0;
}